GET http://localhost:3000/users
Content-Type: application/json


### Cadastro de um usuario
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "Lucas de Souza Pelegrina",
  "email": "lking4@gmail.com",
  "phone": "9123123123",
  "password": "123321123",
  "confirmpassword": "123321123"
}


### Login de um usuario 
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "lking4@gmail.com",
  "password": "123321123"
}


### Checar um usuario
GET http://localhost:3000/users/checkuser
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjYXMgZGUgU291emEgUGVsZWdyaW5hIiwiaWQiOiI2NjMwNTMyZTlkYWQ1YjI1MTU0NGIwMDEiLCJpYXQiOjE3MTQ0NDMxNTF9._1HqhFke31rprnExshIUSZFs0W7vlZrVUOtNjw5eBb4


### Procurar usuario pelo Id
GET http://localhost:3000/users/6630532e9dad5b251544b001
Content-Type: application/json


### Atualização de usuario por Id
Patch http://localhost:3000/users/edit/6630532e9dad5b251544b001
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjYXMgZGUgU291emEgUGVsZWdyaW5hIiwiaWQiOiI2NjMwNTMyZTlkYWQ1YjI1MTU0NGIwMDEiLCJpYXQiOjE3MTQ0NDMxNTF9._1HqhFke31rprnExshIUSZFs0W7vlZrVUOtNjw5eBb4

{
  "name": "Lucas de Souza",
  "email": "lking7@gmail.com",
  "phone": "9123123123",
  "password": "123321123",
  "confirmpassword": "123321123"
}

### Deletar um usuário por Id
Delete http://localhost:3000/users/6630532e9dad5b251544b001
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjYXMgZGUgU291emEgUGVsZWdyaW5hIiwiaWQiOiI2NjMwNTMyZTlkYWQ1YjI1MTU0NGIwMDEiLCJpYXQiOjE3MTQ0NDMxNTF9._1HqhFke31rprnExshIUSZFs0W7vlZrVUOtNjw5eBb4